//
//  Item+CoreDataProperties.swift
//  CoreTasks
//
//  Created by Pasha Bahadori on 8/11/16.
//  Copyright © 2016 Pelican. All rights reserved.
//
//  Choose "Create NSManagedObject Subclass…" from the Core Data editor menu
//  to delete and recreate this implementation file for your updated model.
//

import Foundation
import CoreData

extension Item {

    // The attributes we declared as added as properties of item
    // NSManaged tells the Swift compiler that Core Data provides the storage and implementation for the property declarations at run time
    // This means that when we assign a value to the text property on an instance of Item, the compiler knows that this isn't an ordinary class
    // Core Data is going to handle how the data is stored and saved
    
    // The code generated by Core Data for this NSManagedObject subclass is very little 
    // This class is generated not only so that we can use it in code but also so that we can write any helpers we need for getting data into the right format
    
    
    @NSManaged var text: String?
    @NSManaged var completed: Bool

}
